# Docker Compose development overrides
# Automatically loaded by docker-compose for local development
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/tmp  # For air hot reload cache
    environment:
      - CGO_ENABLED=0
    command: go run cmd/server/main.go
    
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.svelte-kit
